name: pulpitflow
description: "Al-Minbar: A comprehensive Islamic Khutbah preparation app that combines research, writing, and delivery into one seamless workflow."
publish_to: "none"
version: 1.0.6+6

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter_quill: ^11.4.2
  html: ^0.15.6
  flutter_html: ^3.0.0-beta.2
  file_picker: ^8.1.2
  share_plus: ^12.0.0
  printing: ^5.0.0
  pdf: ^3.0.0
  http: ^1.4.0
  permission_handler: ^12.0.1
  device_info_plus: ^12.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  sqflite: ^2.0.0
  path_provider: ^2.0.0
  shared_preferences: ^2.0.0
  supabase_flutter: ^2.10.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/templates/
